#include <stdio.h>

void abs_path();
//void all-set-bits();
//void and-m2n();
//void bit-array();
//void boilerpla();
//void bracket-count();
//void cardinal-test();
//void clock-angle();
//void fast-pow();
//void fib();
//void game-of-life();
//void hops();
//void in-place-k-sort();
//void kaprekar();
//void multi-bracket-count();
//void no-division-division();
//void palintdrome();
//void queue-stack();
//void reg-bal-brackets();
//void rotated-array();
//void run-length-transcoder();
//void sevenish();
//void shortest-substring();
//void sqrt();
//void three-stacks();
//void tower-of-hanoi();
//void url-shortener();
