#include <stdio.h>
#include <string.h> //for strlen in bracket count(s)

void abs_path();
void all_set_bits();
void and_m2n();
void bit_array();
void boilerpla();
void bracket_count();
void cardinal_test();
void clock_angle();
void fast_pow();
void fib();
void game_of_life();
void hops();
void in_place_k_sort();
void kaprekar();
void multi_bracket_count();
void no_division_division();
void palintdrome();
void queue_stack();
void reg_bal_brackets();
void rotated_array();
void run_length_transcoder();
void sevenish();
void shortest_substring();
void msqrt();
void three_stacks();
void tower_of_hanoi();
void url_shortener();
void utf_checker();
void running_median();
void spreadsheet_col_encoder();
void connect_four();
